from enum import Enum


class ErrorCode(str, Enum):
    E_INPUT_REQUIRED = "E_INPUT_REQUIRED"
    E_INPUT_FORMAT_INVALID = "E_INPUT_FORMAT_INVALID"
    E_INPUT_LENGTH_EXCEEDED = "E_INPUT_LENGTH_EXCEEDED"
    E_ENUM_VALUE_INVALID = "E_ENUM_VALUE_INVALID"
    E_RESOURCE_NOT_FOUND = "E_RESOURCE_NOT_FOUND"
    E_CHECKOUT_SELECTION_EMPTY = "E_CHECKOUT_SELECTION_EMPTY"
    E_CHECKOUT_SESSION_MISSING = "E_CHECKOUT_SESSION_MISSING"
    E_SESSION_UNAVAILABLE = "E_SESSION_UNAVAILABLE"
    E_STATE_CONFLICT = "E_STATE_CONFLICT"
    E_WRITE_FAILED = "E_WRITE_FAILED"
    E_SERVICE_UNAVAILABLE = "E_SERVICE_UNAVAILABLE"
